# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import video_streaming_pb2 as video__streaming__pb2


class ImageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VideoLatestImage = channel.unary_unary(
                '/chrys.cloud.videostreaming.v1beta1.Image/VideoLatestImage',
                request_serializer=video__streaming__pb2.VideoFrameRequest.SerializeToString,
                response_deserializer=video__streaming__pb2.VideoFrame.FromString,
                )
        self.VideoBufferedImage = channel.unary_stream(
                '/chrys.cloud.videostreaming.v1beta1.Image/VideoBufferedImage',
                request_serializer=video__streaming__pb2.VideoFrameBufferedRequest.SerializeToString,
                response_deserializer=video__streaming__pb2.VideoFrame.FromString,
                )
        self.VideoProbe = channel.unary_unary(
                '/chrys.cloud.videostreaming.v1beta1.Image/VideoProbe',
                request_serializer=video__streaming__pb2.VideoProbeRequest.SerializeToString,
                response_deserializer=video__streaming__pb2.VideoProbeResponse.FromString,
                )
        self.ListStreams = channel.unary_stream(
                '/chrys.cloud.videostreaming.v1beta1.Image/ListStreams',
                request_serializer=video__streaming__pb2.ListStreamRequest.SerializeToString,
                response_deserializer=video__streaming__pb2.ListStream.FromString,
                )
        self.Annotate = channel.unary_unary(
                '/chrys.cloud.videostreaming.v1beta1.Image/Annotate',
                request_serializer=video__streaming__pb2.AnnotateRequest.SerializeToString,
                response_deserializer=video__streaming__pb2.AnnotateResponse.FromString,
                )
        self.Proxy = channel.unary_unary(
                '/chrys.cloud.videostreaming.v1beta1.Image/Proxy',
                request_serializer=video__streaming__pb2.ProxyRequest.SerializeToString,
                response_deserializer=video__streaming__pb2.ProxyResponse.FromString,
                )
        self.Storage = channel.unary_unary(
                '/chrys.cloud.videostreaming.v1beta1.Image/Storage',
                request_serializer=video__streaming__pb2.StorageRequest.SerializeToString,
                response_deserializer=video__streaming__pb2.StorageResponse.FromString,
                )
        self.SystemTime = channel.unary_unary(
                '/chrys.cloud.videostreaming.v1beta1.Image/SystemTime',
                request_serializer=video__streaming__pb2.SystemTimeRequest.SerializeToString,
                response_deserializer=video__streaming__pb2.SystemTimeResponse.FromString,
                )


class ImageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VideoLatestImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise