# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import video_streaming_pb2 as video__streaming__pb2


class ImageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VideoLatestImage = channel.unary_unary(
                '/chrys.cloud.videostreaming.v1beta1.Image/VideoLatestImage',
                request_serializer=video__streaming__pb2.VideoFrameRequest.SerializeToString,
                response_deserializer=video__streaming__pb2.VideoFrame.FromString,
                )
        self.VideoBufferedImage = channel.unary_stream(
                '/chrys.cloud.videostreaming.v1beta1.Image/VideoBufferedImage',
                request_serializer=video__streaming__pb2.VideoFrameBufferedRequest.SerializeToString,
                response_deserializer=video__streaming__pb2.VideoFrame.FromString,
                )
        self.VideoProbe = channe